user_input1 = input("What is your favorite animal?\n>")
user_input2 = input("What sound does the animal make?\n>")
user_input3 = input("Where do they live?\n>")
user_input4 = input("What is a fun fact about them?\n>")
user_input5 = input("What does it eat?\n>")
print("Your favorite animal is the " + user_input1 + "\nIt makes this sound " + user_input2 + "\nThey live in " + user_input3 + "\nA fun fact about them is " + user_input4 + "\nThey eat " + user_input5)
